In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [2]:
# Carregar microdados do enem
df = pd.read_csv('MICRODADOS_ENEM_2018.csv', encoding='Latin1', sep=';')

In [3]:
#selecionar as provas apenas do estado do Rio Grande do Sul

rs = df[df['SG_UF_PROVA'] == 'RS']

rs.to_csv('rs.csv', index=False)

#rs = pd.read_csv('rs.csv')

In [4]:
#selecionar apenas os estudantes que estiveram presentes nas 4 provas

rs2 = rs[(rs['TP_PRESENCA_CN'] == 1) & (rs['TP_PRESENCA_CH'] == 1) & (rs['TP_PRESENCA_LC'] == 1) & (rs['TP_PRESENCA_MT'] == 1)]

In [5]:
rs2.head()

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_NASCIMENTO,NO_MUNICIPIO_NASCIMENTO,CO_UF_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,IN_BAIXA_VISAO,IN_CEGUEIRA,IN_SURDEZ,IN_DEFICIENCIA_AUDITIVA,IN_SURDO_CEGUEIRA,IN_DEFICIENCIA_FISICA,IN_DEFICIENCIA_MENTAL,IN_DEFICIT_ATENCAO,IN_DISLEXIA,IN_DISCALCULIA,IN_AUTISMO,IN_VISAO_MONOCULAR,IN_OUTRA_DEF,IN_GESTANTE,IN_LACTANTE,IN_IDOSO,IN_ESTUDA_CLASSE_HOSPITALAR,IN_SEM_RECURSO,IN_BRAILLE,IN_AMPLIADA_24,IN_AMPLIADA_18,IN_LEDOR,IN_ACESSO,IN_TRANSCRICAO,IN_LIBRAS,IN_LEITURA_LABIAL,IN_MESA_CADEIRA_RODAS,IN_MESA_CADEIRA_SEPARADA,IN_APOIO_PERNA,IN_GUIA_INTERPRETE,IN_COMPUTADOR,IN_CADEIRA_ESPECIAL,IN_CADEIRA_CANHOTO,IN_CADEIRA_ACOLCHOADA,IN_PROVA_DEITADO,IN_MOBILIARIO_OBESO,IN_LAMINA_OVERLAY,IN_PROTETOR_AURICULAR,IN_MEDIDOR_GLICOSE,IN_MAQUINA_BRAILE,IN_SOROBAN,IN_MARCA_PASSO,IN_SONDA,IN_MEDICAMENTOS,IN_SALA_INDIVIDUAL,IN_SALA_ESPECIAL,IN_SALA_ACOMPANHANTE,IN_MOBILIARIO_ESPECIFICO,IN_MATERIAL_ESPECIFICO,IN_NOME_SOCIAL,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025,Q026,Q027
2,180008202046,2018,4308904,Getúlio Vargas,43,RS,24.0,F,0.0,1,1,4308904.0,Getúlio Vargas,43.0,RS,1,7,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4308904,Getúlio Vargas,43,RS,1.0,1.0,1.0,1.0,447.0,451.0,455.0,459.0,514.7,576.6,512.2,500.7,CDEBDABBEDDAAECACDECECABEECDCAABCDACEBDBBADBE,EDCECBAAEDBEDAEADCACBEAADCAEBDEACBEBADDAECEBC,99999EBCADCDEBDBACADEBDEBAEBCBEABCDDCEDABABEDA...,BDECBDAEEBEDCCDBADBCDDBAEDECCEAECBDDBBDACABEC,1,BDDEDBCACEBCCACDCDDAECAADBDBCEEAEAABEBEBBACED,CACDDBDDECCEDEEEBCEAEECBBEBEDBEDECBEBDCAABCDE,BBDECBBCDBCECBABDBEDACDDBBBEADECACEDBEBABCBEAE...,ACEADCEBBDADAAEBBDDEDABADBEXCCCDBCAEEACBCDDAB,1.0,120.0,120.0,100.0,100.0,100.0,540.0,C,D,C,B,4,H,A,B,C,B,A,B,B,B,A,B,A,A,B,B,A,B,A,C,B,A,A
4,180008787994,2018,4322400,Uruguaiana,43,RS,25.0,F,1.0,1,1,4322400.0,Uruguaiana,43.0,RS,1,7,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4322400,Uruguaiana,43,RS,1.0,1.0,1.0,1.0,450.0,451.0,455.0,461.0,488.4,596.4,438.5,486.2,BCCCAEABEACAADDCBEEDCBBBEBCCADCACACDBBEADCEED,ACEDCBEBCABEBAEEDBEEEBCDDCDADADDABBCEACBABABE,EAECB99999DEABDBECBDEACDCEDEDBBADCBAABBBAADDDA...,BDECAEEAECBACBCEDBCCEEACADBCDACDBADDDCECAEBCC,0,ACEDEAEAEBECAADABBDBCEDEDDCDDABCCACBCACEBDEBB,CACDDBDDECCEDEEEBCEAEECBBEBEDBEDECBEBDCAABCDE,BBDECBBCDBCECBABDBEDACDDBBBEADECACEDBEBABCBEAE...,EBBDEECCCDACEADCBCAAEBBCBCADAEDABADDADDABDBEX,1.0,120.0,120.0,120.0,100.0,80.0,540.0,E,E,C,B,2,B,A,B,C,B,A,B,A,B,A,B,A,A,B,A,A,C,B,B,B,A,A
5,180008411484,2018,4323002,Viamão,43,RS,35.0,F,1.0,1,1,4314902.0,Porto Alegre,43.0,RS,1,12,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4323002,Viamão,43,RS,1.0,1.0,1.0,1.0,448.0,451.0,455.0,460.0,483.1,646.2,518.1,497.0,ACEEAEEBABBBBCEBABDCDCEBAABDCBDBACDBBDAEAACBA,EBCDCBDAEACEBEEEACCCAECADEAEDAEDEEBDBACABBBAE,99999ADCEBCDABABCCACECDCCADACDBDAEAABCDDBBAEEA...,CABAACDCACADDBCBEEDAEDBCABAADECDCDBCBDACDCBCA,1,BCACEEBBBDACEDECAADDDABDBCCACDCBCEDEDABEBEAEA,CACDDBDDECCEDEEEBCEAEECBBEBEDBEDECBEBDCAABCDE,BBDECBBCDBCECBABDBEDACDDBBBEADECACEDBEBABCBEAE...,ADAEDABBCAADBEXEBBDEEADCCCCDACEDDABCBCAAEBBDD,1.0,120.0,40.0,40.0,100.0,0.0,300.0,C,E,C,B,3,E,A,B,C,B,A,B,A,B,A,B,A,A,B,A,B,C,B,B,B,A,A
8,180007286721,2018,4316907,Santa Maria,43,RS,24.0,M,0.0,1,1,4311106.0,Jaguari,43.0,RS,1,7,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4316907,Santa Maria,43,RS,1.0,1.0,1.0,1.0,447.0,453.0,458.0,459.0,566.8,705.9,643.8,653.3,AADBBBDACCBACBEDECDBCBADDCDB.AAABECCDDABBADCE,ECCBBEBEDAEDBDAAAEDEEBEECDCDEDAEAAECAABBEEBCE,BCDEB99999EADCAEAAABCBEDABBCDCBDBBEABBADAEEDEC...,BADBEBDEEBEDADDECBACDABADDEBCECDBCAAEADABBCBD,0,BDDEDBCACEBCCACDCDDAECAADBDBCEEAEAABEBEBBACED,ECCBBEBEDBEDBDDAEECDECBECACDEDEECDECAABBDEBCE,BCDEBDBCBBACDCBEAECBABADBBECECBDBBEABDADACEDEC...,ACEADCEBBDADAAEBBDDEDABADBEXCCCDBCAEEACBCDDAB,1.0,160.0,200.0,180.0,180.0,140.0,860.0,D,B,B,B,20,A,A,B,B,A,A,B,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A
9,180008196168,2018,4305355,Charqueadas,43,RS,38.0,M,0.0,1,1,4318408.0,São Jerônimo,43.0,RS,1,12,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4305355,Charqueadas,43,RS,1.0,1.0,1.0,1.0,448.0,452.0,456.0,460.0,486.7,439.1,511.4,539.3,ABBBECEEABBBBACAABADDCADDABACDCBAACBACEDEEEBA,AAAEACBBBACAD..BBBBCCAAABBECCCCCAAACBCDCBABBB,99999EBCDBABEEDAAABCDABCBACBBACCDBAABCDBABBBAD...,CCBBADBBCCAEABCDBEDBBBACCCCABBDCDABBCCCCBDEEC,1,BCACEEBBBDACEDECAADDDABDBCCACDCBCEDEDABEBEAEA,AEECDECBEBDCACDEDEEDBDDEBCECDECAABEDBEBBEBECC,BBEDCCBBDBBBEADECACEDBEADABEDBABAECCBEABDDBACD...,ADAEDABBCAADBEXEBBDEEADCCCCDACEDDABCBCAAEBBDD,1.0,120.0,120.0,120.0,120.0,60.0,540.0,D,B,D,B,1,C,A,B,C,A,A,B,A,B,A,B,A,A,B,A,A,B,B,B,B,A,A

In [6]:
#filtrar pelas colunas do questionário e outras de possível relevância
questoes = ['Q0' + str(x).zfill(2) for x in range(1,28)]
colunas = ['NU_IDADE', 'TP_SEXO', 'TP_COR_RACA', 'TP_ESTADO_CIVIL', 'TP_ST_CONCLUSAO', 'TP_ESCOLA', 'CO_ESCOLA', 
           'NU_NOTA_CN','NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_MT', 'NU_NOTA_REDACAO']
colunas = colunas + questoes

rs3 = rs2.loc[:, colunas]
rs3.head()

   NU_IDADE TP_SEXO  TP_COR_RACA  TP_ESTADO_CIVIL  TP_ST_CONCLUSAO  TP_ESCOLA  CO_ESCOLA  NU_NOTA_CN  NU_NOTA_CH  NU_NOTA_LC  NU_NOTA_MT  NU_NOTA_REDACAO Q001 Q002 Q003 Q004  Q005 Q006 Q007 Q008 Q009 Q010 Q011 Q012 Q013 Q014 Q015 Q016 Q017 Q018 Q019 Q020 Q021 Q022 Q023 Q024 Q025 Q026 Q027
2      24.0       F            1              0.0                1          1        NaN       514.7       576.6       512.2       500.7            540.0    C    D    C    B     4    H    A    B    C    B    A    B    B    B    A    B    A    A    B    B    A    B    A    C    B    A    A
4      25.0       F            1              1.0                1          1        NaN       488.4       596.4       438.5       486.2            540.0    E    E    C    B     2    B    A    B    C    B    A    B    A    B    A    B    A    A    B    A    A    C    B    B    B    A    A
5      35.0       F            1              1.0                1          1        NaN       483.1       646.2       518.1       497.0            300.0    C    E    C    B     3    E    A    B    C    B    A    B    A    B    A    B    A    A    B    A    B    C    B    B    B    A    A
8      24.0       M            1              0.0                1          1        NaN       566.8       705.9       643.8       653.3            860.0    D    B    B    B    20    A    A    B    B    A    A    B    A    B    A    A    A    A    A    A    A    A    A    A    A    A    A
9      38.0       M            1              0.0                1          1        NaN       486.7       439.1       511.4       539.3            540.0    D    B    D    B     1    C    A    B    C    A    A    B    A    B    A    B    A    A    B    A    A    B    B    B    B    A    A

In [7]:
#salvar em csv
rs3.to_csv('paraModelo.csv', index = False)